config/routes.rb
Rails.application.routes.draw do
  get 'kb_war/index'
  get 'kb_war' => "kb_war#index"
  get 'kb_war/gamestart'

  resources :blog
  get 'blog/page/:id' => "blog#index", as: :blog_page
  get 'blog/quotes'
  get 'test/index'
  get 'teckwu/index'
  root 'teckwu#index'

end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
	validates :title, presence: true,
					  uniqueness: {message: "Title has already been taken."}  
	validates :content, presence: true
	has_many :comments, dependent: :destroy

	def truncated_post(length, seperator = ' ')
		content.truncate(truncate_at=length, 
						  seperator: seperator)
	end

	def self.desc_blogposts(limit, offset)
		self.order(created_at: :desc)
			.limit(limit)
			.offset(offset)
	end

	def long_ordinal
		created_at.to_formatted_s(:long_ordinal)
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blogpost
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def quotes
  end

  def index
  	params_id = params[:id].to_i
  	@id = params_id != 0 ? params_id : 1
  	@blogposts = Blogpost.desc_blogposts(5, (@id-1) * 5)
  	#disable "Older" if last element of @blogposts is of id=1
  	if @blogposts.empty? or @blogposts[-1][:id] == 1
  		@older_disable = true
  	end
  end


  def new
  	@blogpost = Blogpost.new
  end

  def create
  	@blogpost = Blogpost.new permitted_blogpost_attributes

  	if @blogpost.save
  		redirect_to action: "index"
  	else
  		render action: "new"
  	end
  end

  def permitted_blogpost_attributes
  	params.require(:blogpost).permit(:title, :content)
  end
end

app/controllers/bootstraptest_controller.rb
class BootstraptestController < ApplicationController
  def quotes
  end

  def index
  	params_id = params[:id].to_i
  	@id = params_id != 0 ? params_id : 1
  	@blogposts = Blogpost.order(created_at: :desc)
  						 .limit(5)
  						 .offset((@id-1) * 5)
  	#disable "Older" if last element of @blogposts is of id=1
  	unless @blogposts.empty?
  		@older_disable = true if @blogposts[-1][:id] == 1
  	end
  end


  def new
  	@blogpost = Blogpost.new
  end

  def create
  	@blogpost = Blogpost.new permitted_blogpost_attributes

  	if @blogpost.save
  		redirect_to action: "index"
  	else
  		render action: "new"
  	end
  end

  def permitted_blogpost_attributes
  	params.require(:blogpost).permit(:title, :content)
  end
end

app/controllers/kb_war_controller.rb
class KbWarController < ApplicationController
  def index
  end

  def gamestart
  end
end

app/controllers/teckwu_controller.rb
class TeckwuController < ApplicationController
  def index
  	srand
  	cloud_scale = [1.6, 0.7, 1.15, 0.8, 1.33,
  				   0.8, 2, 0.8, 1.4, 1.2,
  				   1.2, 0.5, 1.2, 2, 1.4,
  				   1.5, 1.7, 0.86, 1.3, 1.8]
  	#position, gap
  	def cloud_gap(px, scale, maxscale)
  		scale/maxscale * px * (2.8 + rand * 0.5)
  	end

  	@cloud_parallax = [].tap do |arr|
  		0.upto(cloud_scale.length-1) do |x|
  			rand_num = -10 * x * rand
  			arr << [rand_num, rand_num - cloud_gap(350, 
  					cloud_scale[x], cloud_scale.max),
  					(rand + 0.6) * 70 * x]
  		end
  	end
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  	srand
  	cloud_scale = [1.6, 1.5, 1.55, 0.8, 1.33,
             0.8, 2, 2.1, 1.4, 1.9,
             0.9, 2.5, 0.6, 1.5, 1.4,
             1.8, 1.7, 0.86, 1.3, 1.8];
  	#position, gap
  	def cloud_gap(px, scale, maxscale)
  		scale/maxscale * px * (3.5 + rand * 0.5)
  	end

  	@cloud_parallax = [].tap do |arr|
  		0.upto(cloud_scale.length-1) do |x|
  			rand_num = -50 * x * rand
  			arr << [rand_num, rand_num - cloud_gap(500, 
  					cloud_scale[x], cloud_scale.max),
  					rand * 100 * x]
  		end
  	end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/kb_war_helper.rb
module KbWarHelper
end

app/helpers/teckwu_helper.rb
module TeckwuHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/blog/_head.html.haml
%head
	%meta{name: "author", content: "Ong Teck Wu"}
	%meta{name: "description", content: "Blog"}
	%meta{name: "viewport", content: "width=device-width, initial-scale=1"}
	%meta{"http-equiv" => "X-UA-Compatible", content: "IE=edge"}
	%meta{"charset" => "utf-8"}
	%title =title
	=javascript_include_tag "blog_bundle"
	=stylesheet_link_tag "blog_bundle"

%body
	

app/views/blog/_navbar.html.haml
%nav.navbar-fixed-top
	.container-fluid#navbarhead
		.navbar-header
			%button#shrunkbutton.navbar-toggle{:type => "button", :data => {:toggle => "collapse", :target => "#navbar-target"}}
				%span.sr-only Toggle navigation
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
		.row
			.collapse.navbar-collapse#navbar-target.col-xs-6
				%ul.nav.navbar-nav
					%li.active.dropdown
						%a.li-color.dropdown-toggle{:href => "#", "data-toggle" => "dropdown"} 
							Home
							%span.caret-margin.caret
						%ul.dropdown-menu{:role => "menu"}
							%li
								%a{:href => "#"}Something
							%li
								%a{:href => "#"}Something
							%li.divider
							%li
								%a{:href => "#"}Something else
					%li
						%a.li-color{:href => "#"} Profile
					%li
						%a.li-color{:href => "#"} Messages

			
			%form.navbar-form.hidden-xs.navbar-right{role: "search"}
				.form-group{style: "display:inline;"}
					.input-group
						%input.form-control{:type => "text", :placeholder => "Search"}
						%span.input-group-addon
							%a{:href => ""}
								%span.glyphicon.glyphicon-search

app/views/blog/index.html.haml
!!!
%html
	
	= render "head", locals: {title: "blog"} 
	=stylesheet_link_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css"

	%body

		%header
			= render "navbar"
			.jumbotron#jumbo
				.container
					%h1 Teck Wu's Blog
					%h2.lead I talk about everything I know. Generally code.
					/ %a.btn.btm-primary.btm-lg{:role => "button", :href => "#"} Learn More
		

		.container
			.row
				//blog-posts
				.col-sm-8.col-xs-12.blog-posts
					//sample blog post
					- if @blogposts.empty?
						%p#nothing Nothing to be found here!
					- @blogposts.each do |bp|
						.blog-head
							%h2.blog-post-title
								%a{:href => "#"}= bp[:title] 
							%p.blog-post-meta
								By
								%a{:href => ""}Ong Teck Wu
								| 
								= bp.long_ordinal
								|
								= bp[:id]
							.truncated-blog-post
								= bp.truncated_post(150)
							%a.read-more{:href => "#"}
								Read More...
								%span.arrow-down

							.blog-post.blog-post-show
								%p= bp[:content]
								%a.read-less{:href => '#'} 
									Read Less...
									%span.arrow-up
							%hr

				//blog-sidebar
				.col-sm-3.col-xs-12
					#about-blog
						%h4 About
						%p   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate numquam, illo perferendis iusto vero consequatur quibusdam excepturi! Amet, velit, obcaecati. Ut quibusdam odit excepturi nesciunt non perferendis rerum nemo voluptatem.
					#categories
						%h4#category-title CATEGORIES
						%a.category-name{:href => "#"} 
							Lorem ipsum
							%span.category-num (1) 
				.col-xs-12
					%ul.pager
						%li.previous{class: ("disabled" if @id == 1)}	
							=link_to "Newer", blog_page_path((@id - 1).to_s), class: "page_to", id: "page_#{@id}"
						%li.next{class: ("disabled" if @older_disable)}
							=link_to "Older", blog_page_path((@id + 1).to_s), class: "page_to", id: "page_#{@id}"

app/views/blog/new.html.haml
!!!
%html
	
	= render "head", locals: {title: "new blogpost"} 
	=stylesheet_link_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css"

	%body

		%header
			= render "navbar"

		.container#new-form-container
			.row
				.col-xs-12.col-sm-8
					%h1#new-post New Post
					%hr
					= form_for @blogpost, url: blog_index_path, html: {class:"form"} do |b|
						.form-group
							= b.label :title, class: "form-label"
							= b.text_field(:title, class: "form-control", placeholder: "Title") 
							- if @blogpost.errors[:title]
								- @blogpost.errors[:title].each do |m|
									%p.form-error-message= "#{m}"
						.form-group
							= b.label :content, class: "form-label"
							= b.text_area(:content, class: "form-control", rows: "10", placeholder: "Your Content")
							- if @blogpost.errors[:content]
								- @blogpost.errors[:content].each do |m|
									%p= "#{m}"

						= b.submit(value: "Submit Post")

app/views/blog/quotes.html.haml
!!!
%html
	
	= render "head", locals: {title: "quotes"} 

	%body
		.container-fluid#test
			.row
				.col-xs-12
					%h1 Lorem ipsum dolor sit amet, consectetur.
			.row
				.col-xs-8
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, vel.
				.col-xs-4 
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic earum repellat, doloremque itaque illum <mark> assumenda </mark> tempora suscipit numquam voluptate repudiandae deserunt voluptas iure dolore tempore saepe molestiae ipsam sunt, praesentium!
			.row 
				.col-xs-6
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta, ratione soluta aliquid!
				.col-xs-6
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae laudantium aut, ducimus corrupti. lorem12
			.row
				.col-xs-5
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, unde possimus illum!	
				.col-xs-7
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro sed, sunt totam?
			.row
				.col-xs-8
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque assumenda laboriosam possimus veniam.
				.col-xs-4
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis excepturi saepe impedit a sint, quidem maiores porro facere deserunt dignissimos?
			.row
				.col-xs-4
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt ratione repellat veritatis voluptatem voluptate laboriosam mollitia quia sed at possimus! Dignissimos natus nisi harum modi eos. Aliquid eius, perspiciatis velit eos debitis sequi quos autem, est deserunt accusantium doloremque quae.
				.col-xs-8
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus quae repudiandae accusantium perspiciatis non debitis quo saepe consequuntur iure voluptates.

app/views/blog/show.html.haml
!!!
%html
	
	= render "head", locals: {title: "show"} 
	=stylesheet_link_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css"

	%body

		%header
			= render "navbar"

		.container

app/views/bootstraptest/_head.html.haml
%head
	%meta{name: "author", content: "Ong Teck Wu"}
	%meta{name: "description", content: "Bootstrap Test"}
	%meta{name: "viewport", content: "width=device-width, initial-scale=1"}
	%meta{"http-equiv" => "X-UA-Compatible", content: "IE=edge"}
	%meta{"charset" => "utf-8"}
	%title =title
	=javascript_include_tag "bootstraptest_bundle"
	=stylesheet_link_tag "bootstraptest_bundle"

app/views/bootstraptest/index.html.haml
!!!
%html
	
	= render "head", locals: {title: "bootstraptest"} 
	=stylesheet_link_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css"

	%body

		%header
			= render "navbar"
			.jumbotron#jumbo
				.container
					%h1 Teck Wu's Blog
					%h2.lead I talk about everything I know. Generally code.
					/ %a.btn.btm-primary.btm-lg{:role => "button", :href => "#"} Learn More
			

		.container
			.row
				//blog-posts
				.col-sm-8.col-xs-12.blog-posts
					//sample blog post
					- if @blogposts.empty?
						%p#nothing Nothing to be found here!
					- @blogposts.each do |bp|
						.blog-head
							%h2.blog-post-title
								%a{:href => "#"}= bp[:title] 
							%p.blog-post-meta
								By
								%a{:href => ""}Ong Teck Wu
								| 
								= bp[:created_at].to_formatted_s(:long_ordinal)
								|
								= bp[:id]
							.truncated-blog-post
								=truncate bp[:content], length: 120, seperator: ' '
							%a.read-more{:href => "#"}
								Read More...
								%span.arrow-down

							.blog-post.blog-post-show
								%p= bp[:content]
								%a.read-less{:href => '#'} 
									Read Less...
									%span.arrow-up
							%hr


				//blog-sidebar
				.col-sm-3.col-xs-12
					#about-blog
						%h4 About
						%p   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate numquam, illo perferendis iusto vero consequatur quibusdam excepturi! Amet, velit, obcaecati. Ut quibusdam odit excepturi nesciunt non perferendis rerum nemo voluptatem.
					#categories
						%h4#category-title CATEGORIES
						%a.category-name{:href => "#"} 
							Lorem ipsum
							%span.category-num (1) 
				.col-xs-12
					%ul.pager
						%li.previous{class: ("disabled" if @id == 1)}	
							=link_to "Newer", bootstraptest_page_path((@id - 1).to_s), class: "page_to", id: "page_#{@id}"
						%li.next{class: ("disabled" if @older_disable)}
							=link_to "Older", bootstraptest_page_path((@id + 1).to_s), class: "page_to", id: "page_#{@id}"

app/views/bootstraptest/new.html.haml
!!!
%html
	
	= render "head", locals: {title: "bootstraptest"} 
	=stylesheet_link_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css"

	%body

		%header
			= render "navbar"

		.container#new-form-container
			.row
				.col-xs-12.col-sm-8
					%h1#new-post New Post
					%hr
					= form_for @blogpost, url: bootstraptest_index_path, html: {class:"form"} do |b|
						.form-group
							= b.label :title, class: "form-label"
							= b.text_field(:title, class: "form-control", placeholder: "Title") 
							- if @blogpost.errors[:title]
								- @blogpost.errors[:title].each do |m|
									%p.form-error-message= "#{m}"
						.form-group
							= b.label :content, class: "form-label"
							= b.text_area(:content, class: "form-control", rows: "10", placeholder: "Your Content")
							- if @blogpost.errors[:content]
								- @blogpost.errors[:content].each do |m|
									%p= "#{m}"

						= b.submit(value: "Submit Post")

app/views/bootstraptest/quotes.html.haml
!!!
%html
	
	= render "head", locals: {title: "bootstraptest"} 

	%body
		.container-fluid#test
			.row
				.col-xs-12
					%h1 Lorem ipsum dolor sit amet, consectetur.
			.row
				.col-xs-8
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, vel.
				.col-xs-4 
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic earum repellat, doloremque itaque illum <mark> assumenda </mark> tempora suscipit numquam voluptate repudiandae deserunt voluptas iure dolore tempore saepe molestiae ipsam sunt, praesentium!
			.row 
				.col-xs-6
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta, ratione soluta aliquid!
				.col-xs-6
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae laudantium aut, ducimus corrupti. lorem12
			.row
				.col-xs-5
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, unde possimus illum!	
				.col-xs-7
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro sed, sunt totam?
			.row
				.col-xs-8
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque assumenda laboriosam possimus veniam.
				.col-xs-4
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis excepturi saepe impedit a sint, quidem maiores porro facere deserunt dignissimos?
			.row
				.col-xs-4
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt ratione repellat veritatis voluptatem voluptate laboriosam mollitia quia sed at possimus! Dignissimos natus nisi harum modi eos. Aliquid eius, perspiciatis velit eos debitis sequi quos autem, est deserunt accusantium doloremque quae.
				.col-xs-8
					%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus quae repudiandae accusantium perspiciatis non debitis quo saepe consequuntur iure voluptates.

app/views/kb_war/_head.html.haml
%head
	%meta{name: "author", content: "Ong Teck Wu"}
	%meta{name: "description", content: "Keyboard Warrior"}
	%meta{name: "viewport", content: "width=device-width, initial-scale=1"}
	%meta{"http-equiv" => "X-UA-Compatible", content: "IE=edge"}
	%meta{"charset" => "utf-8"}
	%title Keyboard Warrior
	=javascript_include_tag "kb_war_bundle"
	=stylesheet_link_tag "kb_war_bundle"

app/views/kb_war/gamestart.html.haml
%html
	
	= render "head"

%body{:data => {:title => "game"}}
	.container#alpha-board
		.row
			.col-xs-12.text-center#you-lose
				%p#you-lose-title You Lose.
				%p Final Score:
				%p#you-lose-final-score 0
	.container#alphabets-count
		.row
			.col-xs-12.text-center#alphabets-count-text
				%p#alpha-level Level 1
				%p Alphabets Count:
				%p#alpha-count 0

app/views/kb_war/index.html.haml
%html
	
	= render "head"

%body{:data => {:title => "main"}}
	.container-fluid
		.row
			.col-xs-12#kb-war
				.keyboard-title
					%div K
				.keyboard-title
					%div E
				.keyboard-title
					%div Y
				.keyboard-title
					%div B
				.keyboard-title
					%div O
				.keyboard-title
					%div A
				.keyboard-title
					%div R
				.keyboard-title
					%div D
			.col-xs-12#kb-war2
				.keyboard-title
					%div W
				.keyboard-title
					%div A
				.keyboard-title
					%div R
				.keyboard-title
					%div R
				.keyboard-title
					%div I
				.keyboard-title
					%div O
				.keyboard-title
					%div R
	.container
		.row
			.col-xs-12
				=link_to("Start", kb_war_gamestart_path, class: "center-block btn btn-default btn-lg", id: "block", type: "button", role: "button")
			.col-xs-8.col-xs-offset-2#instructions
				%p Keys will appear from the top of the window. 
				%p Tap the appropriate keyboard button to make a key disappear. 
				%p.lead Do it fast, or else you will lose the game!
	
	%footer
		.container
			.row
				.col-xs-12#footer
					.row
						.col-xs-2.col-xs-offset-10#footer-otw
							%p By Ong Teck Wu

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teckwu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/teckwu/index.html.haml
!!!
%html
    %head
        %title Ong Teck Wu
        = javascript_include_tag "teckwu_bundle"
        = stylesheet_link_tag "teckwu_bundle"

%body#skrollr-body
    #test
    .intro
    #in1.intro2
    #in2.intro2{"data-0" => "display: none;", "data-2500" => "width: 98.8%;", "data-93" => "width: 3.7%;\n                                   display: inline;"}

    %p#introp_titlename.introp Ong Teck Wu
    %p#introp_progressbar.introp Scroll Down

    = image_tag "click-click.jpg", :id => "click_click"
    .contentbox{"data-0" => "top: 0px", "data-150" => "top: 150px"}
        #about.content{"data-0" => "transform:scale(1);left:0%;", "data-150" => "transform:scale(0); left:18%;"}
            %p About
        #projects.content{"data-0" => "transform:scale(1) rotate(0deg);", "data-150" => "transform:scale(0) rotate(900deg);"}
            %p Projects
        #reading_list.content{"data-0" => "transform:scale(1);right:0%;", "data-150" => "transform:scale(0); right:18%;"}
            %p Blog

    #contentbox2
        #about2.content2
        #about3.content3
        #projects2.content2
        #projects3.content3
        #reading_list2.content2
        #reading_list3.content3

    #x1.cloud{"data-0" => "top:-3%", "data-300" => "top:-75%;"}

    .infobox{"data-150" => "top:150px;", "data-200" => "top:268px;", "data-250" => "top:293px;"}

        #info1.info{"data-150" => "transform: scale(0);", "data-225" => "transform: scale(1);", "data-323" => "transform: scale(1);", "data-550" => "transform: scale(0);"}
            %p#title1.infotitle Who Am I?
            %p{:name => "content"} Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas non congue lacus, sed pulvinar lorem. Nam eu iaculis metus. Fusce interdum, nisl a porta congue, lorem felis aliquam elit, consequat porta augue nisl in justo. Pellentesque bibendum lacinia aliquam. Maecenas ultrices metus at vulputate iaculis. Donec malesuada id lacus id pretium. Nunc hendrerit odio lacus, nec dictum velit sollicitudin sit amet. Aenean in eros sed orci luctus semper eu sit amet turpis. Nulla varius leo id metus malesuada, sed placerat mauris vulputate. Nunc varius orci in enim euismod, at vestibulum justo adipiscing.

        .infox
            #info2.info{"data-150" => "transform: scale(0);", "data-225" => "transform: scale(1);", "data-316" => "transform: scale(1);", "data-550" => "transform: scale(0);"}
                %p#title2.infotitle What's Up!
                %p{:name => "content"} dafdsf

            #info3.info{"data-150" => "transform: scale(0);", "data-225" => "transform: scale(1);", "data-316" => "transform: scale(1);", "data-550" => "transform: scale(0);"}
                %p#title3.infotitle Where I've Worked!
                %p{:name => "content"} dafdsf

        .infox
            #info4.info{"data-150" => "transform: scale(0);", "data-225" => "transform: scale(1);", "data-316" => "transform: scale(1);", "data-550" => "transform: scale(0);"}
                %p#title2.infotitle Care To Share?
                %p{:name => "content"} dafdsf

            #info5.info{"data-150" => "transform: scale(0);", "data-225" => "transform: scale(1);", "data-316" => "transform: scale(1);", "data-550" => "transform: scale(0);"}
                %p#title3.infotitle Have A Nice Day!
                %p{:name => "content"} dafdsf

    %div.cloudxs
        -0.upto(19) do |cloud_no|
            %div.cloud.cloudx{"id" => "cloud#{cloud_no + 1}", "data-700" => "top: #{@cloud_parallax[cloud_no][0]}px; left: #{@cloud_parallax[cloud_no][2]}px","data-1500" => "top: #{@cloud_parallax[cloud_no][1]}px;"}

    .skills_and_interests
        %p{"data-1050" => "opacity:1;", "data-1250" => "opacity:0;", "data-700" => "opacity:0;", "data-1000" => "opacity:1;"}Skills And Interests
    %canvas#wordcloud